#!/usr/bin/perl
use warnings;
use strict;
use Module::Release;

my $release = Module::Release->new();

$release->clean();
$release->build_makefile();
$release->make();
$release->test();
$release->disttest();

unlink glob("Data-Throttler-*.tar*");
$release->dist();
